import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import Hero from '../components/Hero';
import Gallery from '../components/Gallery';
import Projects from '../components/Projects';
import Partners from '../components/Partners';
import Featured from '../components/Featured';
import Instagram from '../components/Instagram';
import Footer from '../components/footer';
import Contact from '../components/Contact';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Buildit Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
   </Head>
   <Hero heading='Development company' message='Forward-thinking real estate developer, owner and investor with a reputation.'/>
    <Projects />
    <Partners />
    <Featured />
    <Instagram />
    <Contact />
    <Footer />
   
    </div>
  );
}
